Result for test_case/func_arg_test/test_func_arg.py:
======[pikapython packages installed]======
pikascript-core==v1.13.3 (2024/05/25 01:26:44)
PikaStdLib===v1.13.3
===========================================
~~~/ POWERED BY \~~~
~  pikapython.com  ~
~~~~~~~~~~~~~~~~~~~~
(pikascript) pika compiler:
  compiling main.py...
  linking pikascript-api/pikaModules_cache.py.a...
(pikascript) all succeed.
======= Test Start =======
Test function: test_function_arguments(a, b=2, *args, **kwargs)
Function arguments test:
a: 1
b: 2
*args: ()
**kwargs: {}
a: 1
b: 2
*args: (3,)
**kwargs: {}
a: 1
b: 2
*args: (3, 4, 5, 6)
**kwargs: {}
a: 1
b: 2
*args: (3, 4, 5, 6)
**kwargs: {'177693': 7, '177694': 8}
Function arguments test with keyword arguments:
a: 1
b: 2
*args: ()
Assertion "self != 0" failed, in function: arg_getType(). 
  (at /home/build/linux/../../src/dataArg.h:140)
Aborted
